# Multi-language support for MrZoidbergBot
# Languages: English (EN), German (GER), French (FR), Dutch (NL)

LANGUAGES = {
    'EN': {
        'name': 'English',
        'flag': '🇬🇧',
        'welcome_title': '🌍 {shop_name} 📦 🌏 ✈️',
        'overall_rating': '⭐ Overall Rating: 4.9/5.0',
        'currency': 'Currency: {currency}',
        'payments': 'Payments: {payment_methods}',
        'welcome_user': '👤 <b>Welcome, {first_name}!</b>',
        'welcome_back': '👤 <b>Welcome back, {first_name}!</b>',
        'secret_phrase': '**Your secret phrase code:** {phrase}',
        'available_countries': 'Available countries:',
        'country_ger': '🇩🇪 GER - 🌍 WW',
        'country_aus': '🇦🇺 AUS - 🇦🇺 AUS',
        'country_usa': '🇺🇸 USA - 🇺🇸 USA',
        'store_owner': 'The store owner Mr Worldwide',
        'powered_by': 'Powered by The Engineer',
        'promotion': '✨ {promotion_text} ✨',
        'read_about': '"PLEASE READ \'Show About\' BEFORE"',
        'premium_quality': '✅ Premium quality & best prices',
        'ninja_packaging': '✅ Ninja packaging',
        'worldwide_shipping': '✅ Worldwide shipping',
        'we_ship': '📦 WE SHIP:',
        'shipping_europe': '[🇪🇺 EUROPE]',
        'shipping_aus': '[🇦🇺 AUS]',
        'shipping_usa': '[🇺🇸 USA]',
        'telegram_updates': '📞 Telegram for all latest updates',
        'ceo': 'CEO {ceo}',
        
        # Menu buttons
        'products': '🛍️ Products',
        'my_account': '👤 My Account',
        'search': '🔍 Search',
        'cart': '🛒 Cart (€{total:.2f})',
        'orders': '📦 Orders',
        'wishlist': '🎁 Wishlist',
        'support': '🆘 Support',
        'recommendations': '🎯 Recommendations',
        'updates': '📰 Updates',
        'pgp_key': '🔑 PGP Key',
        'restart_session': '🔄 Restart Session',
        'show_about': '📖 Show About',
        'hide_about': '📖 Hide About',
        'back_to_menu': '🔙 Back to Menu',
        'back_to_main': '🔙 Back to main menu',
        
        # Rating page
        'rating_title': '⭐ **Overall Rating: 4.9/5.0**',
        'customer_reviews': '🌟 **Customer Reviews Summary:**',
        'quality_rating': '✅ **Quality**: 4.9/5.0',
        'delivery_rating': '✅ **Delivery**: 4.8/5.0',
        'packaging_rating': '✅ **Packaging**: 5.0/5.0',
        'communication_rating': '✅ **Communication**: 4.9/5.0',
        'value_rating': '✅ **Value**: 4.8/5.0',
        'based_on_reviews': '📊 **Based on 1,247 customer reviews**',
        'recent_reviews': '💬 **Recent Reviews:**',
        'review_1': '• "Excellent quality and fast delivery!" - ⭐⭐⭐⭐⭐',
        'review_2': '• "Best packaging I\'ve ever seen!" - ⭐⭐⭐⭐⭐',
        'review_3': '• "Great communication and support!" - ⭐⭐⭐⭐⭐',
        'why_customers_love': '🎯 **Why customers love us:**',
        'premium_products': '• Premium quality products',
        'ninja_packaging_desc': '• Ninja packaging for discretion',
        'worldwide_shipping_desc': '• Worldwide shipping',
        'customer_support': '• 24/7 customer support',
        'crypto_payments': '• Secure cryptocurrency payments',
        'thank_you': 'Thank you for trusting us with your orders! 🙏',
        
        # Language selection
        'select_language': '🌐 Select Language / Sprache wählen / Choisir la langue / Taal selecteren',
        'language_set': 'Language set to: {lang_name}',
        
        # Common messages
        'session_restarted': 'Session restarted successfully!',
        'invalid_language': 'Invalid language selection',
        'selected_country': 'Selected country: {country}',
        
        # Checkout and Payment
        'checkout': 'Checkout',
        'invoice': 'Invoice #{invoice_id}',
        'status_pending': 'Status: 🕒 Pending Checkout',
        'enter_details': 'Enter the discount code, payment method, address and delivery method. Once your order has been completed, you will be given payment details.',
        'payment_method': 'Payment Method',
        'discount_code': 'Discount Code',
        'enter_address': 'Enter Address',
        'select_delivery': 'Select Delivery',
        'order_confirm': 'Order Confirm',
        'order_cancel': 'Order Cancel',
        'payment_sent': 'Payment Sent',
        'order_no': 'Order No',
        'order_yes': 'Order Yes',
        'order_paid': 'Order Paid',
        'cart_empty': 'Your cart is empty!',
    },
    
    'GER': {
        'name': 'Deutsch',
        'flag': '🇩🇪',
        'welcome_title': '🌍 {shop_name} 📦 🌏 ✈️',
        'overall_rating': '⭐ Gesamtbewertung: 4,9/5,0',
        'currency': 'Währung: {currency}',
        'payments': 'Zahlungen: {payment_methods}',
        'welcome_user': '👤 <b>Willkommen, {first_name}!</b>',
        'welcome_back': '👤 <b>Willkommen zurück, {first_name}!</b>',
        'secret_phrase': '**Ihr Geheimcode:** {phrase}',
        'available_countries': 'Verfügbare Länder:',
        'country_ger': '🇩🇪 GER - 🌍 WW',
        'country_aus': '🇦🇺 AUS - 🇦🇺 AUS',
        'country_usa': '🇺🇸 USA - 🇺🇸 USA',
        'store_owner': 'Der Ladenbesitzer Mr Worldwide',
        'powered_by': 'Powered by The Engineer',
        'promotion': '✨ {promotion_text} ✨',
        'read_about': '"BITTE \'Über uns anzeigen\' LESEN"',
        'premium_quality': '✅ Premium-Qualität & beste Preise',
        'ninja_packaging': '✅ Ninja-Verpackung',
        'worldwide_shipping': '✅ Weltweiter Versand',
        'we_ship': '📦 WIR VERSENDEN:',
        'shipping_europe': '[🇪🇺 EUROPA]',
        'shipping_aus': '[🇦🇺 AUS]',
        'shipping_usa': '[🇺🇸 USA]',
        'telegram_updates': '📞 Telegram für alle neuesten Updates',
        'ceo': 'CEO {ceo}',
        
        # Menu buttons
        'products': '🛍️ Produkte',
        'my_account': '👤 Mein Konto',
        'search': '🔍 Suche',
        'cart': '🛒 Warenkorb (€{total:.2f})',
        'orders': '📦 Bestellungen',
        'wishlist': '🎁 Wunschliste',
        'support': '🆘 Support',
        'recommendations': '🎯 Empfehlungen',
        'updates': '📰 Updates',
        'pgp_key': '🔑 PGP-Schlüssel',
        'restart_session': '🔄 Sitzung neu starten',
        'show_about': '📖 Über uns anzeigen',
        'hide_about': '📖 Über uns ausblenden',
        'back_to_menu': '🔙 Zurück zum Menü',
        'back_to_main': '🔙 Zurück zum Hauptmenü',
        
        # Rating page
        'rating_title': '⭐ **Gesamtbewertung: 4,9/5,0**',
        'customer_reviews': '🌟 **Kundenbewertungen Zusammenfassung:**',
        'quality_rating': '✅ **Qualität**: 4,9/5,0',
        'delivery_rating': '✅ **Lieferung**: 4,8/5,0',
        'packaging_rating': '✅ **Verpackung**: 5,0/5,0',
        'communication_rating': '✅ **Kommunikation**: 4,9/5,0',
        'value_rating': '✅ **Wert**: 4,8/5,0',
        'based_on_reviews': '📊 **Basierend auf 1.247 Kundenbewertungen**',
        'recent_reviews': '💬 **Aktuelle Bewertungen:**',
        'review_1': '• "Ausgezeichnete Qualität und schnelle Lieferung!" - ⭐⭐⭐⭐⭐',
        'review_2': '• "Beste Verpackung, die ich je gesehen habe!" - ⭐⭐⭐⭐⭐',
        'review_3': '• "Großartige Kommunikation und Support!" - ⭐⭐⭐⭐⭐',
        'why_customers_love': '🎯 **Warum Kunden uns lieben:**',
        'premium_products': '• Premium-Qualitätsprodukte',
        'ninja_packaging_desc': '• Ninja-Verpackung für Diskretion',
        'worldwide_shipping_desc': '• Weltweiter Versand',
        'customer_support': '• 24/7 Kundensupport',
        'crypto_payments': '• Sichere Kryptowährungszahlungen',
        'thank_you': 'Vielen Dank, dass Sie uns mit Ihren Bestellungen vertrauen! 🙏',
        
        # Language selection
        'select_language': '🌐 Sprache wählen / Select Language / Choisir la langue / Taal selecteren',
        'language_set': 'Sprache eingestellt auf: {lang_name}',
        
        # Common messages
        'session_restarted': 'Sitzung erfolgreich neu gestartet!',
        'invalid_language': 'Ungültige Sprachauswahl',
        'selected_country': 'Land ausgewählt: {country}',
        
        # Checkout and Payment
        'checkout': 'Zur Kasse',
        'invoice': 'Rechnung #{invoice_id}',
        'status_pending': 'Status: 🕒 Warten auf Kasse',
        'enter_details': 'Geben Sie den Rabattcode, Zahlungsmethode, Adresse und Liefermethode ein. Sobald Ihre Bestellung abgeschlossen ist, erhalten Sie Zahlungsdetails.',
        'payment_method': 'Zahlungsmethode',
        'discount_code': 'Rabattcode',
        'enter_address': 'Adresse eingeben',
        'select_delivery': 'Lieferung auswählen',
        'order_confirm': 'Bestellung bestätigen',
        'order_cancel': 'Bestellung stornieren',
        'payment_sent': 'Zahlung gesendet',
        'order_no': 'Bestellung Nein',
        'order_yes': 'Bestellung Ja',
        'order_paid': 'Bestellung bezahlt',
        'cart_empty': 'Ihr Warenkorb ist leer!',
    },
    
    'FR': {
        'name': 'Français',
        'flag': '🇫🇷',
        'welcome_title': '🌍 {shop_name} 📦 🌏 ✈️',
        'overall_rating': '⭐ Note globale: 4,9/5,0',
        'currency': 'Devise: {currency}',
        'payments': 'Paiements: {payment_methods}',
        'welcome_user': '👤 <b>Bienvenue, {first_name}!</b>',
        'welcome_back': '👤 <b>Bon retour, {first_name}!</b>',
        'secret_phrase': '**Votre code secret:** {phrase}',
        'available_countries': 'Pays disponibles:',
        'country_ger': '🇩🇪 GER - 🌍 WW',
        'country_aus': '🇦🇺 AUS - 🇦🇺 AUS',
        'country_usa': '🇺🇸 USA - 🇺🇸 USA',
        'store_owner': 'Le propriétaire du magasin Mr Worldwide',
        'powered_by': 'Powered by The Engineer',
        'promotion': '✨ {promotion_text} ✨',
        'read_about': '"VEUILLEZ LIRE \'Afficher À propos\' AVANT"',
        'premium_quality': '✅ Qualité premium et meilleurs prix',
        'ninja_packaging': '✅ Emballage ninja',
        'worldwide_shipping': '✅ Livraison mondiale',
        'we_ship': '📦 NOUS LIVRONS:',
        'shipping_europe': '[🇪🇺 EUROPE]',
        'shipping_aus': '[🇦🇺 AUS]',
        'shipping_usa': '[🇺🇸 USA]',
        'telegram_updates': '📞 Telegram pour toutes les dernières mises à jour',
        'ceo': 'PDG {ceo}',
        
        # Menu buttons
        'products': '🛍️ Produits',
        'my_account': '👤 Mon Compte',
        'search': '🔍 Recherche',
        'cart': '🛒 Panier (€{total:.2f})',
        'orders': '📦 Commandes',
        'wishlist': '🎁 Liste de souhaits',
        'support': '🆘 Support',
        'recommendations': '🎯 Recommandations',
        'updates': '📰 Mises à jour',
        'pgp_key': '🔑 Clé PGP',
        'restart_session': '🔄 Redémarrer la session',
        'show_about': '📖 Afficher À propos',
        'hide_about': '📖 Masquer À propos',
        'back_to_menu': '🔙 Retour au menu',
        'back_to_main': '🔙 Retour au menu principal',
        
        # Rating page
        'rating_title': '⭐ **Note globale: 4,9/5,0**',
        'customer_reviews': '🌟 **Résumé des avis clients:**',
        'quality_rating': '✅ **Qualité**: 4,9/5,0',
        'delivery_rating': '✅ **Livraison**: 4,8/5,0',
        'packaging_rating': '✅ **Emballage**: 5,0/5,0',
        'communication_rating': '✅ **Communication**: 4,9/5,0',
        'value_rating': '✅ **Valeur**: 4,8/5,0',
        'based_on_reviews': '📊 **Basé sur 1 247 avis clients**',
        'recent_reviews': '💬 **Avis récents:**',
        'review_1': '• "Excellente qualité et livraison rapide!" - ⭐⭐⭐⭐⭐',
        'review_2': '• "Meilleur emballage que j\'ai jamais vu!" - ⭐⭐⭐⭐⭐',
        'review_3': '• "Excellente communication et support!" - ⭐⭐⭐⭐⭐',
        'why_customers_love': '🎯 **Pourquoi les clients nous aiment:**',
        'premium_products': '• Produits de qualité premium',
        'ninja_packaging_desc': '• Emballage ninja pour la discrétion',
        'worldwide_shipping_desc': '• Livraison mondiale',
        'customer_support': '• Support client 24/7',
        'crypto_payments': '• Paiements cryptographiques sécurisés',
        'thank_you': 'Merci de nous faire confiance avec vos commandes! 🙏',
        
        # Language selection
        'select_language': '🌐 Choisir la langue / Select Language / Sprache wählen / Taal selecteren',
        'language_set': 'Langue définie sur: {lang_name}',
        
        # Common messages
        'session_restarted': 'Session redémarrée avec succès!',
        'invalid_language': 'Sélection de langue invalide',
        'selected_country': 'Pays sélectionné: {country}',
        
        # Checkout and Payment
        'checkout': 'Commande',
        'invoice': 'Facture #{invoice_id}',
        'status_pending': 'Statut: 🕒 En attente de commande',
        'enter_details': 'Entrez le code de réduction, la méthode de paiement, l\'adresse et la méthode de livraison. Une fois votre commande terminée, vous recevrez les détails de paiement.',
        'payment_method': 'Méthode de paiement',
        'discount_code': 'Code de réduction',
        'enter_address': 'Entrer l\'adresse',
        'select_delivery': 'Sélectionner la livraison',
        'order_confirm': 'Confirmer la commande',
        'order_cancel': 'Annuler la commande',
        'payment_sent': 'Paiement envoyé',
        'order_no': 'Commande Non',
        'order_yes': 'Commande Oui',
        'order_paid': 'Commande payée',
        'cart_empty': 'Votre panier est vide!',
    },
    
    'NL': {
        'name': 'Nederlands',
        'flag': '🇳🇱',
        'welcome_title': '🌍 {shop_name} 📦 🌏 ✈️',
        'overall_rating': '⭐ Algemene beoordeling: 4,9/5,0',
        'currency': 'Valuta: {currency}',
        'payments': 'Betalingen: {payment_methods}',
        'welcome_user': '👤 <b>Welkom, {first_name}!</b>',
        'welcome_back': '👤 <b>Welkom terug, {first_name}!</b>',
        'secret_phrase': '**Uw geheime code:** {phrase}',
        'available_countries': 'Beschikbare landen:',
        'country_ger': '🇩🇪 GER - 🌍 WW',
        'country_aus': '🇦🇺 AUS - 🇦🇺 AUS',
        'country_usa': '🇺🇸 USA - 🇺🇸 USA',
        'store_owner': 'De winke eigenaar Mr Worldwide',
        'powered_by': 'Powered by The Engineer',
        'promotion': '✨ {promotion_text} ✨',
        'read_about': '"LEES \'Over ons tonen\' EERST"',
        'premium_quality': '✅ Premium kwaliteit & beste prijzen',
        'ninja_packaging': '✅ Ninja verpakking',
        'worldwide_shipping': '✅ Wereldwijde verzending',
        'we_ship': '📦 WIJ VERZENDEN:',
        'shipping_europe': '[🇪🇺 EUROPA]',
        'shipping_aus': '[🇦🇺 AUS]',
        'shipping_usa': '[🇺🇸 USA]',
        'telegram_updates': '📞 Telegram voor alle laatste updates',
        'ceo': 'CEO {ceo}',
        
        # Menu buttons
        'products': '🛍️ Producten',
        'my_account': '👤 Mijn Account',
        'search': '🔍 Zoeken',
        'cart': '🛒 Winkelwagen (€{total:.2f})',
        'orders': '📦 Bestellingen',
        'wishlist': '🎁 Verlanglijst',
        'support': '🆘 Ondersteuning',
        'recommendations': '🎯 Aanbevelingen',
        'updates': '📰 Updates',
        'pgp_key': '🔑 PGP Sleutel',
        'restart_session': '🔄 Sessie herstarten',
        'show_about': '📖 Over ons tonen',
        'hide_about': '📖 Over ons verbergen',
        'back_to_menu': '🔙 Terug naar menu',
        'back_to_main': '🔙 Terug naar hoofdmenu',
        
        # Rating page
        'rating_title': '⭐ **Algemene beoordeling: 4,9/5,0**',
        'customer_reviews': '🌟 **Klantbeoordelingen Samenvatting:**',
        'quality_rating': '✅ **Kwaliteit**: 4,9/5,0',
        'delivery_rating': '✅ **Levering**: 4,8/5,0',
        'packaging_rating': '✅ **Verpakking**: 5,0/5,0',
        'communication_rating': '✅ **Communicatie**: 4,9/5,0',
        'value_rating': '✅ **Waarde**: 4,8/5,0',
        'based_on_reviews': '📊 **Gebaseerd op 1.247 klantbeoordelingen**',
        'recent_reviews': '💬 **Recente beoordelingen:**',
        'review_1': '• "Uitstekende kwaliteit en snelle levering!" - ⭐⭐⭐⭐⭐',
        'review_2': '• "Beste verpakking die ik ooit heb gezien!" - ⭐⭐⭐⭐⭐',
        'review_3': '• "Geweldige communicatie en ondersteuning!" - ⭐⭐⭐⭐⭐',
        'why_customers_love': '🎯 **Waarom klanten van ons houden:**',
        'premium_products': '• Premium kwaliteitsproducten',
        'ninja_packaging_desc': '• Ninja verpakking voor discretie',
        'worldwide_shipping_desc': '• Wereldwijde verzending',
        'customer_support': '• 24/7 klantenservice',
        'crypto_payments': '• Veilige cryptocurrency betalingen',
        'thank_you': 'Bedankt dat u ons vertrouwt met uw bestellingen! 🙏',
        
        # Language selection
        'select_language': '🌐 Taal selecteren / Select Language / Sprache wählen / Choisir la langue',
        'language_set': 'Taal ingesteld op: {lang_name}',
        
        # Common messages
        'session_restarted': 'Sessie succesvol herstart!',
        'invalid_language': 'Ongeldige taalselectie',
        'selected_country': 'Land geselecteerd: {country}',
        
        # Checkout and Payment
        'checkout': 'Afrekenen',
        'invoice': 'Factuur #{invoice_id}',
        'status_pending': 'Status: 🕒 Wachten op afrekenen',
        'enter_details': 'Voer de kortingscode, betaalmethode, adres en leveringsmethode in. Zodra uw bestelling is voltooid, krijgt u betalingsgegevens.',
        'payment_method': 'Betaalmethode',
        'discount_code': 'Kortingscode',
        'enter_address': 'Adres invoeren',
        'select_delivery': 'Levering selecteren',
        'order_confirm': 'Bestelling bevestigen',
        'order_cancel': 'Bestelling annuleren',
        'payment_sent': 'Betaling verzonden',
        'order_no': 'Bestelling Nee',
        'order_yes': 'Bestelling Ja',
        'order_paid': 'Bestelling betaald',
        'cart_empty': 'Uw winkelwagen is leeg!',
    }
}

def get_text(language, key, **kwargs):
    """Get translated text for a given language and key"""
    if language not in LANGUAGES:
        language = 'EN'  # Default to English
    
    if key not in LANGUAGES[language]:
        # Fallback to English if key not found
        if key in LANGUAGES['EN']:
            return LANGUAGES['EN'][key].format(**kwargs)
        return key  # Return key if not found anywhere
    
    return LANGUAGES[language][key].format(**kwargs)

def get_available_languages():
    """Get list of available languages"""
    return [(code, LANGUAGES[code]['name'], LANGUAGES[code]['flag']) for code in LANGUAGES.keys()]

def is_valid_language(language_code):
    """Check if language code is valid"""
    return language_code in LANGUAGES
