# Multi-language support for MrZoidbergBot
# Languages: English (EN), German (GER), French (FR), Dutch (NL)

LANGUAGES = {
    'EN': {
        'name': 'English',
        'flag': '🇬🇧',
        'welcome_title': '🌍 {shop_name} 📦 🌏 ✈️',
        'overall_rating': '⭐ Overall Rating: 4.9/5.0',
        'currency': 'Currency: {currency}',
        'payments': 'Payments: {payment_methods}',
        'welcome_user': '👤 <b>Welcome, {first_name}!</b>',
        'welcome_back': '👤 <b>Welcome back, {first_name}!</b>',
        'secret_phrase': '**Your secret phrase code:** {phrase}',
        'available_countries': 'Available countries:',
        'country_ger': '🇩🇪 GER - 🌍 WW',
        'country_aus': '🇦🇺 AUS - 🇦🇺 AUS',
        'country_usa': '🇺🇸 USA - 🇺🇸 USA',
        'store_owner': 'The store owner Mr Worldwide',
        'powered_by': 'Powered by The Engineer',
        'promotion': '✨ {promotion_text} ✨',
        'read_about': '"PLEASE READ \'Show About\' BEFORE"',
        'premium_quality': '✅ Premium quality & best prices',
        'ninja_packaging': '✅ Ninja packaging',
        'worldwide_shipping': '✅ Worldwide shipping',
        'we_ship': '📦 WE SHIP:',
        'shipping_europe': '[🇪🇺 EUROPE]',
        'shipping_aus': '[🇦🇺 AUS]',
        'shipping_usa': '[🇺🇸 USA]',
        'telegram_updates': '📞 Telegram for all latest updates',
        'ceo': 'CEO {ceo}',
        
        # Menu buttons
        'products': '🛍️ Products',
        'my_account': '👤 My Account',
        'search': '🔍 Search',
        'cart': '🛒 Cart (€{total:.2f})',
        'orders': '📦 Orders',
        'wishlist': '🎁 Wishlist',
        'support': '🆘 Support',
        'recommendations': '🎯 Recommendations',
        'updates': '📰 Updates',
        'pgp_key': '🔑 PGP Key',
        'restart_session': '🔄 Restart Session',
        'show_about': '📖 Show About',
        'hide_about': '📖 Hide About',
        'back_to_menu': '🔙 Back to Menu',
        'back_to_main': '🔙 Back to main menu',
        
        # Rating page
        'rating_title': '⭐ **Overall Rating: 4.9/5.0**',
        'customer_reviews': '🌟 **Customer Reviews Summary:**',
        'quality_rating': '✅ **Quality**: 4.9/5.0',
        'delivery_rating': '✅ **Delivery**: 4.8/5.0',
        'packaging_rating': '✅ **Packaging**: 5.0/5.0',
        'communication_rating': '✅ **Communication**: 4.9/5.0',
        'value_rating': '✅ **Value**: 4.8/5.0',
        'based_on_reviews': '📊 **Based on 1,247 customer reviews**',
        'recent_reviews': '💬 **Recent Reviews:**',
        'review_1': '• "Excellent quality and fast delivery!" - ⭐⭐⭐⭐⭐',
        'review_2': '• "Best packaging I\'ve ever seen!" - ⭐⭐⭐⭐⭐',
        'review_3': '• "Great communication and support!" - ⭐⭐⭐⭐⭐',
        'why_customers_love': '🎯 **Why customers love us:**',
        'premium_products': '• Premium quality products',
        'ninja_packaging_desc': '• Ninja packaging for discretion',
        'worldwide_shipping_desc': '• Worldwide shipping',
        'customer_support': '• 24/7 customer support',
        'crypto_payments': '• Secure cryptocurrency payments',
        'thank_you': 'Thank you for trusting us with your orders! 🙏',
        
        # Language selection
        'select_language': '🌐 Select Language / Sprache wählen / Choisir la langue / Taal selecteren',
        'language_set': 'Language set to: {lang_name}',
        
        # Common messages
        'session_restarted': 'Session restarted successfully!',
        'invalid_language': 'Invalid language selection',
        'selected_country': 'Selected country: {country}',
        
        # Checkout and Payment
        'checkout': 'Checkout',
        'invoice': 'Invoice #{invoice_id}',
        'status_pending': 'Status: 🕒 Pending Checkout',
        'enter_details': 'Enter the discount code, payment method, address and delivery method. Once your order has been completed, you will be given payment details.',
        'payment_method': 'Payment Method',
        'discount_code': 'Discount Code',
        'enter_address': 'Enter Address',
        'select_delivery': 'Select Delivery',
        'order_confirm': 'Order Confirm',
        'order_cancel': 'Order Cancel',
        'payment_sent': 'Payment Sent',
        'order_no': 'Order No',
        'order_yes': 'Order Yes',
        'order_paid': 'Order Paid',
        'cart_empty': 'Your cart is empty!',
        
        # Phrase verification
        'invalid_phrase': 'Invalid Phrase Code',
        'phrase_incorrect': 'The phrase code you entered is incorrect.',
        'your_secret_phrase': 'Your secret phrase',
        'note_enter_phrase': 'Note: Enter the phrase code (not your user ID above).',
        'try_again_or_contact': 'Please try again with the correct phrase code, or contact admin if you don\'t have it.',
        'secret_phrase_too_short': 'Secret Phrase Too Short',
        'phrase_must_be_20_chars': 'Your secret phrase code must be at least 20 characters long.',
        'current_length': 'Current length',
        'characters': 'characters',
        'required': 'Required',
        'create_longer_phrase': 'Please create a longer secret phrase code and try again.',
        'example': 'Example',
        'secret_phrase_too_long': 'Secret Phrase Too Long',
        'phrase_must_be_40_chars': 'Your secret phrase code must be 40 characters or less.',
        'create_shorter_phrase': 'Please create a shorter secret phrase code and try again.',
        'secret_phrase_set': 'Secret Phrase Set',
        'phrase_saved_successfully': 'Your secret phrase code has been saved successfully.',
        'phrase_instructions': 'You can now use this phrase code for future access.',
        
        # Discount and checkout
        'discount_applied': 'Discount Applied Successfully!',
        'code': 'Code',
        'discount': 'Discount',
        'amount_saved': 'Amount Saved',
        'description': 'Description',
        'cart_total': 'Cart Total',
        'new_total': 'New Total',
        'continue_order': 'Continue with your order!',
        'back_to_checkout': 'Back to checkout',
        'discount_error': 'Discount Error',
        'try_again': 'Please try again.',
        
        # Address handling
        'address_received': 'Address Received',
        'address_confirmed': 'Your delivery address has been confirmed.',
        'delivery_address': 'Delivery Address',
        'select_delivery_method': 'Please select your delivery method.',
        
        # Settings and Notifications
        'notification_settings': 'Notification Settings',
        'notification_options': 'Notification Options',
        'current_settings': 'Current Settings',
        'notification_note': 'You can customize your notification preferences here.',
        'language_settings': 'Language Settings',
        'current_language': 'Current Language',
        'language_note': 'Select your preferred language for the bot interface.',
        
        # Notification handlers
        'email_notifications': 'Email Notifications',
        'email_settings': 'Email Settings',
        'current_status': 'Current Status',
        'email_note': 'Manage your email notification preferences.',
        'push_notifications': 'Push Notifications',
        'push_settings': 'Push Settings',
        'push_note': 'Manage your push notification preferences.',
        'disable_all_notifications': 'Disable All Notifications',
        'disable_warning': 'Warning:',
        'disable_confirm': 'Are you sure you want to disable all notifications?',
        'disable_note': 'You can re-enable notifications anytime from settings.',
    },
    
    'GER': {
        'name': 'Deutsch',
        'flag': '🇩🇪',
        'welcome_title': '🌍 {shop_name} 📦 🌏 ✈️',
        'overall_rating': '⭐ Gesamtbewertung: 4,9/5,0',
        'currency': 'Währung: {currency}',
        'payments': 'Zahlungen: {payment_methods}',
        'welcome_user': '👤 <b>Willkommen, {first_name}!</b>',
        'welcome_back': '👤 <b>Willkommen zurück, {first_name}!</b>',
        'secret_phrase': '**Ihr Geheimcode:** {phrase}',
        'available_countries': 'Verfügbare Länder:',
        'country_ger': '🇩🇪 GER - 🌍 WW',
        'country_aus': '🇦🇺 AUS - 🇦🇺 AUS',
        'country_usa': '🇺🇸 USA - 🇺🇸 USA',
        'store_owner': 'Der Ladenbesitzer Mr Worldwide',
        'powered_by': 'Powered by The Engineer',
        'promotion': '✨ {promotion_text} ✨',
        'read_about': '"BITTE \'Über uns anzeigen\' LESEN"',
        'premium_quality': '✅ Premium-Qualität & beste Preise',
        'ninja_packaging': '✅ Ninja-Verpackung',
        'worldwide_shipping': '✅ Weltweiter Versand',
        'we_ship': '📦 WIR VERSENDEN:',
        'shipping_europe': '[🇪🇺 EUROPA]',
        'shipping_aus': '[🇦🇺 AUS]',
        'shipping_usa': '[🇺🇸 USA]',
        'telegram_updates': '📞 Telegram für alle neuesten Updates',
        'ceo': 'CEO {ceo}',
        
        # Menu buttons
        'products': '🛍️ Produkte',
        'my_account': '👤 Mein Konto',
        'search': '🔍 Suche',
        'cart': '🛒 Warenkorb (€{total:.2f})',
        'orders': '📦 Bestellungen',
        'wishlist': '🎁 Wunschliste',
        'support': '🆘 Support',
        'recommendations': '🎯 Empfehlungen',
        'updates': '📰 Updates',
        'pgp_key': '🔑 PGP-Schlüssel',
        'restart_session': '🔄 Sitzung neu starten',
        'show_about': '📖 Über uns anzeigen',
        'hide_about': '📖 Über uns ausblenden',
        'back_to_menu': '🔙 Zurück zum Menü',
        'back_to_main': '🔙 Zurück zum Hauptmenü',
        
        # Rating page
        'rating_title': '⭐ **Gesamtbewertung: 4,9/5,0**',
        'customer_reviews': '🌟 **Kundenbewertungen Zusammenfassung:**',
        'quality_rating': '✅ **Qualität**: 4,9/5,0',
        'delivery_rating': '✅ **Lieferung**: 4,8/5,0',
        'packaging_rating': '✅ **Verpackung**: 5,0/5,0',
        'communication_rating': '✅ **Kommunikation**: 4,9/5,0',
        'value_rating': '✅ **Wert**: 4,8/5,0',
        'based_on_reviews': '📊 **Basierend auf 1.247 Kundenbewertungen**',
        'recent_reviews': '💬 **Aktuelle Bewertungen:**',
        'review_1': '• "Ausgezeichnete Qualität und schnelle Lieferung!" - ⭐⭐⭐⭐⭐',
        'review_2': '• "Beste Verpackung, die ich je gesehen habe!" - ⭐⭐⭐⭐⭐',
        'review_3': '• "Großartige Kommunikation und Support!" - ⭐⭐⭐⭐⭐',
        'why_customers_love': '🎯 **Warum Kunden uns lieben:**',
        'premium_products': '• Premium-Qualitätsprodukte',
        'ninja_packaging_desc': '• Ninja-Verpackung für Diskretion',
        'worldwide_shipping_desc': '• Weltweiter Versand',
        'customer_support': '• 24/7 Kundensupport',
        'crypto_payments': '• Sichere Kryptowährungszahlungen',
        'thank_you': 'Vielen Dank, dass Sie uns mit Ihren Bestellungen vertrauen! 🙏',
        
        # Language selection
        'select_language': '🌐 Sprache wählen / Select Language / Choisir la langue / Taal selecteren',
        'language_set': 'Sprache eingestellt auf: {lang_name}',
        
        # Common messages
        'session_restarted': 'Sitzung erfolgreich neu gestartet!',
        'invalid_language': 'Ungültige Sprachauswahl',
        'selected_country': 'Land ausgewählt: {country}',
        
        # Checkout and Payment
        'checkout': 'Zur Kasse',
        'invoice': 'Rechnung #{invoice_id}',
        'status_pending': 'Status: 🕒 Warten auf Kasse',
        'enter_details': 'Geben Sie den Rabattcode, Zahlungsmethode, Adresse und Liefermethode ein. Sobald Ihre Bestellung abgeschlossen ist, erhalten Sie Zahlungsdetails.',
        'payment_method': 'Zahlungsmethode',
        'discount_code': 'Rabattcode',
        'enter_address': 'Adresse eingeben',
        'select_delivery': 'Lieferung auswählen',
        'order_confirm': 'Bestellung bestätigen',
        'order_cancel': 'Bestellung stornieren',
        'payment_sent': 'Zahlung gesendet',
        'order_no': 'Bestellung Nein',
        'order_yes': 'Bestellung Ja',
        'order_paid': 'Bestellung bezahlt',
        'cart_empty': 'Ihr Warenkorb ist leer!',
        
        # Phrase verification
        'invalid_phrase': 'Ungültiger Phrase-Code',
        'phrase_incorrect': 'Der eingegebene Phrase-Code ist falsch.',
        'your_secret_phrase': 'Ihr Geheimcode',
        'note_enter_phrase': 'Hinweis: Geben Sie den Phrase-Code ein (nicht Ihre Benutzer-ID oben).',
        'try_again_or_contact': 'Bitte versuchen Sie es erneut mit dem korrekten Phrase-Code oder kontaktieren Sie den Admin.',
        'secret_phrase_too_short': 'Geheimcode zu kurz',
        'phrase_must_be_20_chars': 'Ihr Geheimcode muss mindestens 20 Zeichen lang sein.',
        'current_length': 'Aktuelle Länge',
        'characters': 'Zeichen',
        'required': 'Erforderlich',
        'create_longer_phrase': 'Bitte erstellen Sie einen längeren Geheimcode und versuchen Sie es erneut.',
        'example': 'Beispiel',
        'secret_phrase_too_long': 'Geheimcode zu lang',
        'phrase_must_be_40_chars': 'Ihr Geheimcode muss 40 Zeichen oder weniger haben.',
        'create_shorter_phrase': 'Bitte erstellen Sie einen kürzeren Geheimcode und versuchen Sie es erneut.',
        'secret_phrase_set': 'Geheimcode gesetzt',
        'phrase_saved_successfully': 'Ihr Geheimcode wurde erfolgreich gespeichert.',
        'phrase_instructions': 'Sie können diesen Phrase-Code für zukünftigen Zugang verwenden.',
        
        # Discount and checkout
        'discount_applied': 'Rabatt erfolgreich angewendet!',
        'code': 'Code',
        'discount': 'Rabatt',
        'amount_saved': 'Gesparte Summe',
        'description': 'Beschreibung',
        'cart_total': 'Warenkorb Gesamt',
        'new_total': 'Neue Gesamtsumme',
        'continue_order': 'Mit Ihrer Bestellung fortfahren!',
        'back_to_checkout': 'Zurück zur Kasse',
        'discount_error': 'Rabattfehler',
        'try_again': 'Bitte versuchen Sie es erneut.',
        
        # Address handling
        'address_received': 'Adresse erhalten',
        'address_confirmed': 'Ihre Lieferadresse wurde bestätigt.',
        'delivery_address': 'Lieferadresse',
        'select_delivery_method': 'Bitte wählen Sie Ihre Liefermethode.',
        
        # Settings and Notifications
        'notification_settings': 'Benachrichtigungseinstellungen',
        'notification_options': 'Benachrichtigungsoptionen',
        'current_settings': 'Aktuelle Einstellungen',
        'notification_note': 'Sie können Ihre Benachrichtigungseinstellungen hier anpassen.',
        'language_settings': 'Spracheinstellungen',
        'current_language': 'Aktuelle Sprache',
        'language_note': 'Wählen Sie Ihre bevorzugte Sprache für die Bot-Oberfläche.',
        
        # Notification handlers
        'email_notifications': 'E-Mail-Benachrichtigungen',
        'email_settings': 'E-Mail-Einstellungen',
        'current_status': 'Aktueller Status',
        'email_note': 'Verwalten Sie Ihre E-Mail-Benachrichtigungseinstellungen.',
        'push_notifications': 'Push-Benachrichtigungen',
        'push_settings': 'Push-Einstellungen',
        'push_note': 'Verwalten Sie Ihre Push-Benachrichtigungseinstellungen.',
        'disable_all_notifications': 'Alle Benachrichtigungen deaktivieren',
        'disable_warning': 'Warnung:',
        'disable_confirm': 'Sind Sie sicher, dass Sie alle Benachrichtigungen deaktivieren möchten?',
        'disable_note': 'Sie können Benachrichtigungen jederzeit in den Einstellungen wieder aktivieren.',
    },
    
    'FR': {
        'name': 'Français',
        'flag': '🇫🇷',
        'welcome_title': '🌍 {shop_name} 📦 🌏 ✈️',
        'overall_rating': '⭐ Note globale: 4,9/5,0',
        'currency': 'Devise: {currency}',
        'payments': 'Paiements: {payment_methods}',
        'welcome_user': '👤 <b>Bienvenue, {first_name}!</b>',
        'welcome_back': '👤 <b>Bon retour, {first_name}!</b>',
        'secret_phrase': '**Votre code secret:** {phrase}',
        'available_countries': 'Pays disponibles:',
        'country_ger': '🇩🇪 GER - 🌍 WW',
        'country_aus': '🇦🇺 AUS - 🇦🇺 AUS',
        'country_usa': '🇺🇸 USA - 🇺🇸 USA',
        'store_owner': 'Le propriétaire du magasin Mr Worldwide',
        'powered_by': 'Powered by The Engineer',
        'promotion': '✨ {promotion_text} ✨',
        'read_about': '"VEUILLEZ LIRE \'Afficher À propos\' AVANT"',
        'premium_quality': '✅ Qualité premium et meilleurs prix',
        'ninja_packaging': '✅ Emballage ninja',
        'worldwide_shipping': '✅ Livraison mondiale',
        'we_ship': '📦 NOUS LIVRONS:',
        'shipping_europe': '[🇪🇺 EUROPE]',
        'shipping_aus': '[🇦🇺 AUS]',
        'shipping_usa': '[🇺🇸 USA]',
        'telegram_updates': '📞 Telegram pour toutes les dernières mises à jour',
        'ceo': 'PDG {ceo}',
        
        # Menu buttons
        'products': '🛍️ Produits',
        'my_account': '👤 Mon Compte',
        'search': '🔍 Recherche',
        'cart': '🛒 Panier (€{total:.2f})',
        'orders': '📦 Commandes',
        'wishlist': '🎁 Liste de souhaits',
        'support': '🆘 Support',
        'recommendations': '🎯 Recommandations',
        'updates': '📰 Mises à jour',
        'pgp_key': '🔑 Clé PGP',
        'restart_session': '🔄 Redémarrer la session',
        'show_about': '📖 Afficher À propos',
        'hide_about': '📖 Masquer À propos',
        'back_to_menu': '🔙 Retour au menu',
        'back_to_main': '🔙 Retour au menu principal',
        
        # Rating page
        'rating_title': '⭐ **Note globale: 4,9/5,0**',
        'customer_reviews': '🌟 **Résumé des avis clients:**',
        'quality_rating': '✅ **Qualité**: 4,9/5,0',
        'delivery_rating': '✅ **Livraison**: 4,8/5,0',
        'packaging_rating': '✅ **Emballage**: 5,0/5,0',
        'communication_rating': '✅ **Communication**: 4,9/5,0',
        'value_rating': '✅ **Valeur**: 4,8/5,0',
        'based_on_reviews': '📊 **Basé sur 1 247 avis clients**',
        'recent_reviews': '💬 **Avis récents:**',
        'review_1': '• "Excellente qualité et livraison rapide!" - ⭐⭐⭐⭐⭐',
        'review_2': '• "Meilleur emballage que j\'ai jamais vu!" - ⭐⭐⭐⭐⭐',
        'review_3': '• "Excellente communication et support!" - ⭐⭐⭐⭐⭐',
        'why_customers_love': '🎯 **Pourquoi les clients nous aiment:**',
        'premium_products': '• Produits de qualité premium',
        'ninja_packaging_desc': '• Emballage ninja pour la discrétion',
        'worldwide_shipping_desc': '• Livraison mondiale',
        'customer_support': '• Support client 24/7',
        'crypto_payments': '• Paiements cryptographiques sécurisés',
        'thank_you': 'Merci de nous faire confiance avec vos commandes! 🙏',
        
        # Language selection
        'select_language': '🌐 Choisir la langue / Select Language / Sprache wählen / Taal selecteren',
        'language_set': 'Langue définie sur: {lang_name}',
        
        # Common messages
        'session_restarted': 'Session redémarrée avec succès!',
        'invalid_language': 'Sélection de langue invalide',
        'selected_country': 'Pays sélectionné: {country}',
        
        # Checkout and Payment
        'checkout': 'Commande',
        'invoice': 'Facture #{invoice_id}',
        'status_pending': 'Statut: 🕒 En attente de commande',
        'enter_details': 'Entrez le code de réduction, la méthode de paiement, l\'adresse et la méthode de livraison. Une fois votre commande terminée, vous recevrez les détails de paiement.',
        'payment_method': 'Méthode de paiement',
        'discount_code': 'Code de réduction',
        'enter_address': 'Entrer l\'adresse',
        'select_delivery': 'Sélectionner la livraison',
        'order_confirm': 'Confirmer la commande',
        'order_cancel': 'Annuler la commande',
        'payment_sent': 'Paiement envoyé',
        'order_no': 'Commande Non',
        'order_yes': 'Commande Oui',
        'order_paid': 'Commande payée',
        'cart_empty': 'Votre panier est vide!',
        
        # Phrase verification
        'invalid_phrase': 'Code Phrase Invalide',
        'phrase_incorrect': 'Le code phrase que vous avez entré est incorrect.',
        'your_secret_phrase': 'Votre phrase secrète',
        'note_enter_phrase': 'Note: Entrez le code phrase (pas votre ID utilisateur ci-dessus).',
        'try_again_or_contact': 'Veuillez réessayer avec le bon code phrase, ou contactez l\'admin si vous ne l\'avez pas.',
        'secret_phrase_too_short': 'Phrase Secrète Trop Courte',
        'phrase_must_be_20_chars': 'Votre code phrase secrète doit contenir au moins 20 caractères.',
        'current_length': 'Longueur actuelle',
        'characters': 'caractères',
        'required': 'Requis',
        'create_longer_phrase': 'Veuillez créer un code phrase secrète plus long et réessayer.',
        'example': 'Exemple',
        'secret_phrase_too_long': 'Phrase Secrète Trop Longue',
        'phrase_must_be_40_chars': 'Votre code phrase secrète doit contenir 40 caractères ou moins.',
        'create_shorter_phrase': 'Veuillez créer un code phrase secrète plus court et réessayer.',
        'secret_phrase_set': 'Phrase Secrète Définie',
        'phrase_saved_successfully': 'Votre code phrase secrète a été sauvegardé avec succès.',
        'phrase_instructions': 'Vous pouvez maintenant utiliser ce code phrase pour un accès futur.',
        
        # Discount and checkout
        'discount_applied': 'Réduction Appliquée avec Succès!',
        'code': 'Code',
        'discount': 'Réduction',
        'amount_saved': 'Montant Économisé',
        'description': 'Description',
        'cart_total': 'Total du Panier',
        'new_total': 'Nouveau Total',
        'continue_order': 'Continuez avec votre commande!',
        'back_to_checkout': 'Retour à la commande',
        'discount_error': 'Erreur de Réduction',
        'try_again': 'Veuillez réessayer.',
        
        # Address handling
        'address_received': 'Adresse Reçue',
        'address_confirmed': 'Votre adresse de livraison a été confirmée.',
        'delivery_address': 'Adresse de Livraison',
        'select_delivery_method': 'Veuillez sélectionner votre méthode de livraison.',
        
        # Settings and Notifications
        'notification_settings': 'Paramètres de Notification',
        'notification_options': 'Options de Notification',
        'current_settings': 'Paramètres Actuels',
        'notification_note': 'Vous pouvez personnaliser vos préférences de notification ici.',
        'language_settings': 'Paramètres de Langue',
        'current_language': 'Langue Actuelle',
        'language_note': 'Sélectionnez votre langue préférée pour l\'interface du bot.',
        
        # Notification handlers
        'email_notifications': 'Notifications Email',
        'email_settings': 'Paramètres Email',
        'current_status': 'Statut Actuel',
        'email_note': 'Gérez vos préférences de notification par email.',
        'push_notifications': 'Notifications Push',
        'push_settings': 'Paramètres Push',
        'push_note': 'Gérez vos préférences de notification push.',
        'disable_all_notifications': 'Désactiver Toutes les Notifications',
        'disable_warning': 'Avertissement:',
        'disable_confirm': 'Êtes-vous sûr de vouloir désactiver toutes les notifications?',
        'disable_note': 'Vous pouvez réactiver les notifications à tout moment dans les paramètres.',
    },
    
    'NL': {
        'name': 'Nederlands',
        'flag': '🇳🇱',
        'welcome_title': '🌍 {shop_name} 📦 🌏 ✈️',
        'overall_rating': '⭐ Algemene beoordeling: 4,9/5,0',
        'currency': 'Valuta: {currency}',
        'payments': 'Betalingen: {payment_methods}',
        'welcome_user': '👤 <b>Welkom, {first_name}!</b>',
        'welcome_back': '👤 <b>Welkom terug, {first_name}!</b>',
        'secret_phrase': '**Uw geheime code:** {phrase}',
        'available_countries': 'Beschikbare landen:',
        'country_ger': '🇩🇪 GER - 🌍 WW',
        'country_aus': '🇦🇺 AUS - 🇦🇺 AUS',
        'country_usa': '🇺🇸 USA - 🇺🇸 USA',
        'store_owner': 'De winke eigenaar Mr Worldwide',
        'powered_by': 'Powered by The Engineer',
        'promotion': '✨ {promotion_text} ✨',
        'read_about': '"LEES \'Over ons tonen\' EERST"',
        'premium_quality': '✅ Premium kwaliteit & beste prijzen',
        'ninja_packaging': '✅ Ninja verpakking',
        'worldwide_shipping': '✅ Wereldwijde verzending',
        'we_ship': '📦 WIJ VERZENDEN:',
        'shipping_europe': '[🇪🇺 EUROPA]',
        'shipping_aus': '[🇦🇺 AUS]',
        'shipping_usa': '[🇺🇸 USA]',
        'telegram_updates': '📞 Telegram voor alle laatste updates',
        'ceo': 'CEO {ceo}',
        
        # Menu buttons
        'products': '🛍️ Producten',
        'my_account': '👤 Mijn Account',
        'search': '🔍 Zoeken',
        'cart': '🛒 Winkelwagen (€{total:.2f})',
        'orders': '📦 Bestellingen',
        'wishlist': '🎁 Verlanglijst',
        'support': '🆘 Ondersteuning',
        'recommendations': '🎯 Aanbevelingen',
        'updates': '📰 Updates',
        'pgp_key': '🔑 PGP Sleutel',
        'restart_session': '🔄 Sessie herstarten',
        'show_about': '📖 Over ons tonen',
        'hide_about': '📖 Over ons verbergen',
        'back_to_menu': '🔙 Terug naar menu',
        'back_to_main': '🔙 Terug naar hoofdmenu',
        
        # Rating page
        'rating_title': '⭐ **Algemene beoordeling: 4,9/5,0**',
        'customer_reviews': '🌟 **Klantbeoordelingen Samenvatting:**',
        'quality_rating': '✅ **Kwaliteit**: 4,9/5,0',
        'delivery_rating': '✅ **Levering**: 4,8/5,0',
        'packaging_rating': '✅ **Verpakking**: 5,0/5,0',
        'communication_rating': '✅ **Communicatie**: 4,9/5,0',
        'value_rating': '✅ **Waarde**: 4,8/5,0',
        'based_on_reviews': '📊 **Gebaseerd op 1.247 klantbeoordelingen**',
        'recent_reviews': '💬 **Recente beoordelingen:**',
        'review_1': '• "Uitstekende kwaliteit en snelle levering!" - ⭐⭐⭐⭐⭐',
        'review_2': '• "Beste verpakking die ik ooit heb gezien!" - ⭐⭐⭐⭐⭐',
        'review_3': '• "Geweldige communicatie en ondersteuning!" - ⭐⭐⭐⭐⭐',
        'why_customers_love': '🎯 **Waarom klanten van ons houden:**',
        'premium_products': '• Premium kwaliteitsproducten',
        'ninja_packaging_desc': '• Ninja verpakking voor discretie',
        'worldwide_shipping_desc': '• Wereldwijde verzending',
        'customer_support': '• 24/7 klantenservice',
        'crypto_payments': '• Veilige cryptocurrency betalingen',
        'thank_you': 'Bedankt dat u ons vertrouwt met uw bestellingen! 🙏',
        
        # Language selection
        'select_language': '🌐 Taal selecteren / Select Language / Sprache wählen / Choisir la langue',
        'language_set': 'Taal ingesteld op: {lang_name}',
        
        # Common messages
        'session_restarted': 'Sessie succesvol herstart!',
        'invalid_language': 'Ongeldige taalselectie',
        'selected_country': 'Land geselecteerd: {country}',
        
        # Checkout and Payment
        'checkout': 'Afrekenen',
        'invoice': 'Factuur #{invoice_id}',
        'status_pending': 'Status: 🕒 Wachten op afrekenen',
        'enter_details': 'Voer de kortingscode, betaalmethode, adres en leveringsmethode in. Zodra uw bestelling is voltooid, krijgt u betalingsgegevens.',
        'payment_method': 'Betaalmethode',
        'discount_code': 'Kortingscode',
        'enter_address': 'Adres invoeren',
        'select_delivery': 'Levering selecteren',
        'order_confirm': 'Bestelling bevestigen',
        'order_cancel': 'Bestelling annuleren',
        'payment_sent': 'Betaling verzonden',
        'order_no': 'Bestelling Nee',
        'order_yes': 'Bestelling Ja',
        'order_paid': 'Bestelling betaald',
        'cart_empty': 'Uw winkelwagen is leeg!',
        
        # Phrase verification
        'invalid_phrase': 'Ongeldige Phrase Code',
        'phrase_incorrect': 'De phrase code die u heeft ingevoerd is onjuist.',
        'your_secret_phrase': 'Uw geheime phrase',
        'note_enter_phrase': 'Opmerking: Voer de phrase code in (niet uw gebruikers-ID hierboven).',
        'try_again_or_contact': 'Probeer opnieuw met de juiste phrase code, of neem contact op met admin als u deze niet heeft.',
        'secret_phrase_too_short': 'Geheime Phrase Te Kort',
        'phrase_must_be_20_chars': 'Uw geheime phrase code moet minimaal 20 tekens lang zijn.',
        'current_length': 'Huidige lengte',
        'characters': 'tekens',
        'required': 'Vereist',
        'create_longer_phrase': 'Maak een langere geheime phrase code en probeer opnieuw.',
        'example': 'Voorbeeld',
        'secret_phrase_too_long': 'Geheime Phrase Te Lang',
        'phrase_must_be_40_chars': 'Uw geheime phrase code moet 40 tekens of minder zijn.',
        'create_shorter_phrase': 'Maak een kortere geheime phrase code en probeer opnieuw.',
        'secret_phrase_set': 'Geheime Phrase Ingesteld',
        'phrase_saved_successfully': 'Uw geheime phrase code is succesvol opgeslagen.',
        'phrase_instructions': 'U kunt deze phrase code nu gebruiken voor toekomstige toegang.',
        
        # Discount and checkout
        'discount_applied': 'Korting Succesvol Toegepast!',
        'code': 'Code',
        'discount': 'Korting',
        'amount_saved': 'Bespaard Bedrag',
        'description': 'Beschrijving',
        'cart_total': 'Winkelwagen Totaal',
        'new_total': 'Nieuw Totaal',
        'continue_order': 'Ga door met uw bestelling!',
        'back_to_checkout': 'Terug naar afrekenen',
        'discount_error': 'Kortingsfout',
        'try_again': 'Probeer opnieuw.',
        
        # Address handling
        'address_received': 'Adres Ontvangen',
        'address_confirmed': 'Uw bezorgadres is bevestigd.',
        'delivery_address': 'Bezorgadres',
        'select_delivery_method': 'Selecteer uw bezorgmethode.',
        
        # Settings and Notifications
        'notification_settings': 'Meldingen Instellingen',
        'notification_options': 'Meldingen Opties',
        'current_settings': 'Huidige Instellingen',
        'notification_note': 'U kunt uw meldingsvoorkeuren hier aanpassen.',
        'language_settings': 'Taal Instellingen',
        'current_language': 'Huidige Taal',
        'language_note': 'Selecteer uw voorkeurstaal voor de bot-interface.',
        
        # Notification handlers
        'email_notifications': 'E-mail Meldingen',
        'email_settings': 'E-mail Instellingen',
        'current_status': 'Huidige Status',
        'email_note': 'Beheer uw e-mail meldingsvoorkeuren.',
        'push_notifications': 'Push Meldingen',
        'push_settings': 'Push Instellingen',
        'push_note': 'Beheer uw push meldingsvoorkeuren.',
        'disable_all_notifications': 'Alle Meldingen Uitschakelen',
        'disable_warning': 'Waarschuwing:',
        'disable_confirm': 'Weet u zeker dat u alle meldingen wilt uitschakelen?',
        'disable_note': 'U kunt meldingen op elk moment opnieuw inschakelen in de instellingen.',
    }
}

def get_text(language, key, **kwargs):
    """Get translated text for a given language and key"""
    if language not in LANGUAGES:
        language = 'EN'  # Default to English
    
    if key not in LANGUAGES[language]:
        # Fallback to English if key not found
        if key in LANGUAGES['EN']:
            return LANGUAGES['EN'][key].format(**kwargs)
        return key  # Return key if not found anywhere
    
    return LANGUAGES[language][key].format(**kwargs)

def get_available_languages():
    """Get list of available languages"""
    return [(code, LANGUAGES[code]['name'], LANGUAGES[code]['flag']) for code in LANGUAGES.keys()]

def is_valid_language(language_code):
    """Check if language code is valid"""
    return language_code in LANGUAGES
